name: classification
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - pytorch
  - torchvision
  - nltk
  - spacy
  - gensim
  - yellowbrick
  - pip
  - pip:
    - transformers
    - datasets
    - sentence-transformers
    - imbalanced-learn