name: mdp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=22.0
  # Scientific computing
  - numpy>=1.21
  - scipy>=1.7
  - pandas>=1.3

  # Visualization
  - matplotlib>=3.4
  - seaborn>=0.11

  # Jupyter (optional, for development and visualization)
  - jupyter
  - ipykernel

  # Additional useful tools
  - tqdm  # for progress bars

  # Dependencies that need to be installed via pip
  - pip:
    - gymnasium
    - bettermdptools
    - pygame  # required for gymnasium rendering
