name: unsupervised
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - scikit-learn
    - jupyter
    - ipykernel
    - yellowbrick
    - scipy
    - kneed